language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
before_install:
  - sudo rm -f /etc/boto.cfg
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r test-requirements.txt
script:
  - make run-tests